import Head from 'next/head'
import Image from 'next/image'
import { Noto_Sans } from 'next/font/google'
import Header from '@/components/Header'
import Unsplash from '@/components/Unsplash'

const notoSans = Noto_Sans({ weight:["500", "700"], subsets: ['latin'] })

export default function Home() {
  return (
    <div className='px-32 py-8 flex flex-col gap-16'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={notoSans.className}>
        <Header />
      </header>
      <main className={notoSans.className}>
        <Unsplash />
      </main>
    </div>
  )
}
